<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogProject.DataAccessLayer\BlogProject.DataAccessLayer.csproj" />
    <ProjectReference Include="..\BlogProject.EntityLayer\BlogProject.EntityLayer.csproj" />
    <ProjectReference Include="..\BlogProject.BusinessLayer\BlogProject.BusinessLayer.csproj" />
  </ItemGroup>

</Project>
